map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

upstream dexa_api {
  server api:3000;
}

# Aplikasi karyawan
server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html/employee;

  include /etc/nginx/snippets/proxy-api.conf;
}

# Portal admin HRD
server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html/admin;

  include /etc/nginx/snippets/proxy-api.conf;
}
